#!/bin/bash -e
cd "$(dirname $0)"/..

source ./scripts/variables

./scripts/build-image

docker tag $SERVICE_NAME $IMAGE_NAME:$TAG
docker tag $SERVICE_NAME $IMAGE_NAME:latest
# Login ECR
aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin $REGISTRY_NAME
# Push to Repository
docker push $IMAGE_NAME:$TAG
docker push $IMAGE_NAME:latest
if [[ $ENV == 'prod' ]]; then
  docker tag $SERVICE_NAME $IMAGE_NAME:$ENV-$TAG
  docker push $IMAGE_NAME:$ENV-$TAG
fi
