apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: datadog-agent-{{ include "<%= name %>-service.serviceAccountName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: datadog
subjects:
  - kind: ServiceAccount
    name:  {{ include "<%= name %>-service.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
