apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "<%= name %>-service.fullname" . }}
  annotations:
    rollme: {{ randAlphaNum 5 | quote }}
spec:
  refreshInterval: "0"
  secretStoreRef:
    name: ssm-vault
    kind: ClusterSecretStore
  data:
  {{- range $key, $val := .Values.env.secret }}
    - secretKey: {{ $key }}
      remoteRef:
        key: {{ $val }}
  {{- end}}
